[workspace]
members = [
    "core",
    "datatypes",
    # "examples/basic",
    # "examples/basic_dispatching",
    # "examples/enc_conns",
    # "examples/measuring_sec",
    # "examples/ml_qos",
    # "examples/open_vpn",
    # "examples/combined",
    # "examples/websites",
    # "tests/functionality/basic_test",
    # "tests/functionality/basic_streaming",
    # "tests/functionality/basic_tracked", "tests/functionality/weird_combos", "tests/functionality/filter_test",
    "examples/flow_collect", "examples/flow_features", "examples/flow_test", "examples/flow_labels",
    # "examples/loss_test", "examples/timeout_test", "examples/tls_quic",
    # "examples/tls_quic_drop",
    # "examples/tls_quic_measure",
]
resolver = "2"

[profile.release]
lto = true

[patch.crates-io]
pcap = { git = 'https://github.com/thegwan/pcap', branch = 'compile-optimized' }

