[package]
name = "flow_collect"
version = "0.1.0"
edition = "2024"

[dependencies]
iris-core = { path = "../../core" }
iris-datatypes = { path = "../../datatypes" }
iris-compiler = { path = "../../compiler" }
serde = "1.0.228"

array-init = "2.1"
csv = "1"
const_format = "0.2"

flow_features = { path = "../flow_features" }